# Default configuration for the Data Mining Project

general:
  artifacts_dir: artifacts
  figures_dir: reports/figures
  random_state: 42

data:
  source: yfinance  # options: kaggle|yfinance
  tickers: [AAPL, MSFT, GOOGL]
  start_date: 2016-01-01
  end_date: 2024-12-31
  interval: 1d

features:
  rsi_window: 14
  sma_windows: [5, 10, 20]
  volatility_window: 10

model:
  type: random_forest  # options: logistic_regression|random_forest
  test_size: 0.2
  n_estimators: 200
  max_depth: 6

live:
  provider: finnhub  # options: finnhub|yfinance
  poll_seconds: 60
  default_ticker: AAPL

llm:
  provider: openai
  model: gpt-4o-mini
  max_news: 10
  use_vader_fallback: true
